title: John Smith
description: My Personal Blog
author: John Smith
logo: http://aboutashu.com/hcz-jekyll-blog/static/img/avatar.png
github: https://github.com/ashutosh2k12
about: Freelance developer

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

url: "http://aboutashu.com/hcz-jekyll-blog"
baseurl: "/hcz-jekyll-blog"
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
